GET http://localhost:5000/posts

###

# register a new user
POST http://localhost:5000/register
Content-Type: application/json

{
    "email": "test@test.be",
    "password": "test"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "test@test.be",
    "password": "test"
}

###

PUT http://localhost:5000/users/a41fe111-22b4-4f1a-83e6-40aabb5106aa
Content-Type: application/json
# Authorization: Bearer <token>

{
    "email": "test@test.be",
    "username": "testy",
}