GET http://localhost:5000/posts

###

# register a new user
POST http://localhost:5000/register
Content-Type: application/json

{
    "email": "test@test.be",
    "password": "test"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "test@test.be",
    "password": "test"
}

###

# get all posts
GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljNjdjYjkyLThiNzMtNGRiMi1iMmU2LWQ5MzlmNGZkOWMyOSIsImVtYWlsIjoidGVzdEB0ZXN0LmJlIiwiaWF0IjoxNjY3MDc1MDQ4LCJleHAiOjE2NjcwNzg2NDh9.L23AMhn13h5-rE_6_VxRquaNNLeK2idmujndmqruzMw

###

# create a new post
POST http://localhost:5000/posts
Authorization: Bearer 
Content-Type: application/json

{
    "title": "test",
    "content": "test",
    "category": "test"
}