GET http://localhost:5000/users

###

# Create a new user
POST http://localhost:5000/users
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "test@test.be",
    "password": "test"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "test@test.be",
    "password": "test"
}